import { cellArea } from 'h3-js';
import fs from 'node:fs';
import path from 'node:path';

import type { CellStats } from '@/scripts/buildingFootprint/downloadBuildingFootprint';

export type ProcessedCellStats = {
  h3Index: string;
  buildingCount: number;
  avgBuildingHeightM: number;
  totalFootprintAreaM2: number;
  buildingCoverageRatio: number;
  buildingCoverageScore: number;
  buildingHeightScore: number;
};

const INPUT_DIR = '.'; // current directory
const OUTPUT_FILE = './building-footprint-coalesced.json';

/**
 * Reads h3 cell data from any `building-footprint-*.json` files
 * generated by `downloadBuildingFootprint.ts`. Merges duplicate cells.
 */
const readH3CellData = (): Map<string, CellStats> => {
  const merged = new Map<string, CellStats>();

  const files = fs
    .readdirSync(INPUT_DIR)
    .filter(
      file =>
        file.startsWith('building-footprint-')
        && file.endsWith('.json')
    )
    .sort();

  console.log(`Found ${files.length} files`);

  for (const file of files) {
    const fPath = path.join(INPUT_DIR, file);

    const fData = JSON.parse(
      fs.readFileSync(fPath, 'utf8')
    ) as Record<string, CellStats>;

    let processed = 0;

    for (const [h3Index, stats] of Object.entries(fData)) {
      const existing = merged.get(h3Index);

      if (existing) {
        existing.buildingCount += stats.buildingCount;
        existing.heightSumM += stats.heightSumM;
        existing.totalFootprintAreaM2 +=
          stats.totalFootprintAreaM2;
      } else {
        merged.set(h3Index, {
          buildingCount: stats.buildingCount,
          heightSumM: stats.heightSumM,
          totalFootprintAreaM2: stats.totalFootprintAreaM2,
        });
      }

      processed += 1;
    }

    console.log(
      `Read in ${file} (${processed.toLocaleString()} cells)`
    );
  }

  console.log(
    `Total unique h3 cells: ${merged.size.toLocaleString()}`
  );

  return merged;
};

/**
 * Helper to get percentile value from array
 */
const getPercentile = (arr: number[], p: number) => {
  const index = (arr.length - 1) * p;
  const lower = Math.floor(index);
  const upper = Math.ceil(index);

  return lower === upper ?
      arr[lower]
    : arr[lower]
        + (arr[upper] - arr[lower]) * (index - lower);
};

/**
 * Adds derived metrics.
 */
const computeDerivedMetrics = (
  cells: Map<string, CellStats>
): ProcessedCellStats[] => {
  const intermediate: Omit<
    ProcessedCellStats,
    'buildingCoverageScore' | 'buildingHeightScore'
  >[] = [...cells.entries()].map(([h3, f]) => ({
    h3Index: h3,
    buildingCount: f.buildingCount,
    avgBuildingHeightM:
      f.buildingCount > 0 ?
        f.heightSumM / f.buildingCount
      : 0,
    totalFootprintAreaM2: f.totalFootprintAreaM2,
    buildingCoverageRatio: Math.min(
      f.totalFootprintAreaM2 / cellArea(h3, 'm2'),
      1
    ),
  }));

  const maxCoverageRatio = Math.max(
    ...intermediate.map(r => r.buildingCoverageRatio)
  );

  // use capped max for height normalization due to outliers
  const heights = intermediate
    .map(r => r.avgBuildingHeightM)
    .sort((a, b) => a - b);
  const maxAvgHeightCapped = getPercentile(heights, 0.999);

  return intermediate.map(f => ({
    ...f,
    buildingCoverageScore:
      f.buildingCoverageRatio / maxCoverageRatio,
    buildingHeightScore:
      Math.min(f.avgBuildingHeightM, maxAvgHeightCapped)
      / maxAvgHeightCapped,
  }));
};

const saveResults = (cells: ProcessedCellStats[]) => {
  fs.writeFileSync(OUTPUT_FILE, JSON.stringify(cells));
  console.log(
    `Saved ${cells.length.toLocaleString()} processed cells to ${OUTPUT_FILE}`
  );
};

const main = () => {
  const cells = readH3CellData();
  const processedCells = computeDerivedMetrics(cells);
  saveResults(processedCells);
  console.log('Done');
};

main();
